client_config_backend: settings
client_config:
  client_id: 110004041576-npdq1rigncg4ebck3lil8ngfhvs3qrbg.apps.googleusercontent.com
  client_secret: KrVS_6sB0157nXaiL8-cCsl7

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
